language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"

deploy:
  provider: openshift
  user: "aa1ronham@gmail.com"
  password:
    - secure: "DS4Jb8l3otZGvkEjNZjGJtM1C5F0Nu6x50M/FjriHxZfAbYHoGbCTAZZb0JmjI16BJfCjkHVfDTwur1FHdn5D311CVE1vObkPP4ANz7kUNIXYqgDseGfKS7rOK1XtQTZ7FGSGoG+x2EvBZrWdimUTn/LGMj6qHZ2WaEQ4cUKhCk="
  app: browserquest
  domain: teambq

notifications:
  irc: "irc.synirc.net#browserquest"
